theme: jekyll-theme-minimal
title: Welcome to the kaestro's homepage!
description: Gatherings of computational knowledges that aren't in coded format, or that isn't enough to be in repository's format
