name: Count Recommended Posts

on:
  push:
    branches:
      - main

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
              ruby-version: 2.7

      - name: Count recommended posts and update file
        run: |
              require 'yaml'
              recommended_count = Dir.glob('_posts/**/*.md').count { |f| File.read(f).include?('recommended: true') }
              File.write('_data/recommended_count.yml', { 'count' => recommended_count }.to_yaml)
              puts "Counted #{recommended_count} recommended posts"

      - name: Commit changes
        run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add _data/recommended_count.yml
              git commit -m "Update recommended count" || echo "No changes to commit"
              git push